# roles/your_role/tasks/build_docker_image.yml


- name: Install Docker Python package
  pip:
    name: docker
    state: present
  become: yes
  
- name: Create Dockerfile
  template:
    src: Dockerfile.j2
    dest:  /opt/django-app/Dockerfile
  become: yes

- name: Build Docker Image
  docker_image:
    name: your-django-app
    path: /opt/django-app/
    state: present
  become: yes

